version: '3.8'
services:
  prompt-library:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/ncecere/prompt-library:latest  # Commented out as we're building locally
    ports:
      - "3300:3000"
    volumes:
      - ./prompts:/app/prompts
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
